apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp
 
spec:
  selector:
    matchLabels:
      app: my-web-app
  replicas: 3

   
  template:
    metadata:
      name: my-web-pod
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: daimashal874/teamimage
        imagePullPolicy: IfNotPresent

        ports:
          - containerPort: 80